/**
 * Site-specific demo content — generated by SiteAssembler
 * Site: Chute do Interior
 * DO NOT EDIT MANUALLY
 */

export interface Category {
  id: string;
  name: string;
  slug: string;
  description?: string;
}

export interface Article {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  category: string;
  categorySlug: string;
  author: string;
  publishedAt: string;
  imageUrl?: string;
  isVideo?: boolean;
  readCount?: number;
  featured?: boolean;
  keyPoints?: string[];
}

export interface BreakingHeadline {
  id: string;
  text: string;
  slug?: string;
  urgent?: boolean;
}

export interface AlertItem {
  id: string;
  level: string;
  title: string;
  href?: string;
  publishedAt: string;
}

export interface LiveUpdate {
  id: string;
  at: string;
  source: string;
  text: string;
}

export interface LiveStory {
  id: string;
  slug: string;
  title: string;
  summary: string;
  updatedAt: string;
  updates: LiveUpdate[];
}

export const categories: Category[] = [
  {
    "id": "cat-serie-c-clubs",
    "name": "Série C clubs",
    "slug": "serie-c-clubs",
    "description": "Cobertura de Série C clubs em Chute do Interior"
  },
  {
    "id": "cat-regional-stories",
    "name": "regional stories",
    "slug": "regional-stories",
    "description": "Cobertura de regional stories em Chute do Interior"
  },
  {
    "id": "cat-grassroots-journeys",
    "name": "grassroots journeys",
    "slug": "grassroots-journeys",
    "description": "Cobertura de grassroots journeys em Chute do Interior"
  }
];

export const breakingHeadlines: BreakingHeadline[] = [
  {
    "id": "brk-1",
    "text": "AO VIVO — Série C clubs: atualização urgente para leitores de Chute do Interior",
    "slug": "ultima-hora-em-serie-c-clubs-decisoes-que-mexem-com-a-rodada-2ks",
    "urgent": true
  },
  {
    "id": "brk-2",
    "text": "AO VIVO — regional stories: atualização urgente para leitores de Chute do Interior",
    "slug": "serie-c-clubs-em-foco-tres-leituras-que-importam-hoje-2kt",
    "urgent": false
  },
  {
    "id": "brk-3",
    "text": "AO VIVO — grassroots journeys: atualização urgente para leitores de Chute do Interior",
    "slug": "por-que-serie-c-clubs-domina-a-conversa-e-o-que-vem-a-seguir-2ku",
    "urgent": false
  }
];

export const articles: Article[] = [
  {
    "id": "art-1",
    "slug": "ultima-hora-em-serie-c-clubs-decisoes-que-mexem-com-a-rodada-2ks",
    "title": "Última hora em Série C clubs: decisões que mexem com a rodada",
    "excerpt": "Leitura direta para quem acompanha Série C clubs no celular — sem enrolação.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Chute do Interior</strong> na seção <em>Série C clubs</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "Série C clubs",
    "categorySlug": "serie-c-clubs",
    "author": "Elena Prado",
    "publishedAt": "2026-09-26T11:06:05.631Z",
    "imageUrl": "https://images.unsplash.com/photo-1486286701208-1d58e9338013?w=800&q=80",
    "readCount": 14540,
    "featured": true,
    "isVideo": true
  },
  {
    "id": "art-2",
    "slug": "serie-c-clubs-em-foco-tres-leituras-que-importam-hoje-2kt",
    "title": "Série C clubs em foco: três leituras que importam hoje",
    "excerpt": "Cobertura rápida e objetiva sobre Série C clubs, com contexto e próximos capítulos.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Chute do Interior</strong> na seção <em>Série C clubs</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "Série C clubs",
    "categorySlug": "serie-c-clubs",
    "author": "Felipe Nunes",
    "publishedAt": "2026-09-29T04:06:05.631Z",
    "imageUrl": "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&q=80",
    "readCount": 15537,
    "featured": true,
    "isVideo": false
  },
  {
    "id": "art-3",
    "slug": "por-que-serie-c-clubs-domina-a-conversa-e-o-que-vem-a-seguir-2ku",
    "title": "Por que Série C clubs domina a conversa — e o que vem a seguir",
    "excerpt": "O que já está confirmado, o que ainda é especulação e o que acompanhar nas próximas horas.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Chute do Interior</strong> na seção <em>Série C clubs</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "Série C clubs",
    "categorySlug": "serie-c-clubs",
    "author": "Gabriela Lopes",
    "publishedAt": "2026-09-28T21:06:05.631Z",
    "imageUrl": "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800&q=80",
    "readCount": 16534,
    "featured": false,
    "isVideo": false
  },
  {
    "id": "art-4",
    "slug": "chute-do-interior-explica-o-ponto-chave-de-regional-stories-nesta-semana-2kv",
    "title": "Chute do Interior explica: o ponto-chave de regional stories nesta semana",
    "excerpt": "Leitura direta para quem acompanha regional stories no celular — sem enrolação.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Chute do Interior</strong> na seção <em>regional stories</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "regional stories",
    "categorySlug": "regional-stories",
    "author": "Hugo Almeida",
    "publishedAt": "2026-09-28T14:06:05.631Z",
    "imageUrl": "https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=800&q=80",
    "readCount": 17531,
    "featured": false,
    "isVideo": false
  },
  {
    "id": "art-5",
    "slug": "regional-stories-o-que-muda-agora-e-o-impacto-direto-para-o-publico-de-c-2kw",
    "title": "regional stories: o que muda agora e o impacto direto para o público de Chute do Interior",
    "excerpt": "Cobertura rápida e objetiva sobre regional stories, com contexto e próximos capítulos.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Chute do Interior</strong> na seção <em>regional stories</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "regional stories",
    "categorySlug": "regional-stories",
    "author": "Ana Ribeiro",
    "publishedAt": "2026-09-28T07:06:05.631Z",
    "imageUrl": "https://images.unsplash.com/photo-1574629810360-7abcae5a4a2a?w=800&q=80",
    "readCount": 18528,
    "featured": false,
    "isVideo": false
  },
  {
    "id": "art-6",
    "slug": "bastidores-de-regional-stories-analise-com-numeros-e-contexto-2kx",
    "title": "Bastidores de regional stories — análise com números e contexto",
    "excerpt": "O que já está confirmado, o que ainda é especulação e o que acompanhar nas próximas horas.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Chute do Interior</strong> na seção <em>regional stories</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "regional stories",
    "categorySlug": "regional-stories",
    "author": "Bruno Costa",
    "publishedAt": "2026-09-28T00:06:05.631Z",
    "imageUrl": "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&q=80",
    "readCount": 19525,
    "featured": false,
    "isVideo": false
  },
  {
    "id": "art-7",
    "slug": "ultima-hora-em-grassroots-journeys-decisoes-que-mexem-com-a-rodada-2ky",
    "title": "Última hora em grassroots journeys: decisões que mexem com a rodada",
    "excerpt": "Leitura direta para quem acompanha grassroots journeys no celular — sem enrolação.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Chute do Interior</strong> na seção <em>grassroots journeys</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "grassroots journeys",
    "categorySlug": "grassroots-journeys",
    "author": "Camila Souza",
    "publishedAt": "2026-09-27T17:06:05.631Z",
    "imageUrl": "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&q=80",
    "readCount": 20522,
    "featured": false,
    "isVideo": false
  },
  {
    "id": "art-8",
    "slug": "grassroots-journeys-em-foco-tres-leituras-que-importam-hoje-2kz",
    "title": "grassroots journeys em foco: três leituras que importam hoje",
    "excerpt": "Cobertura rápida e objetiva sobre grassroots journeys, com contexto e próximos capítulos.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Chute do Interior</strong> na seção <em>grassroots journeys</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "grassroots journeys",
    "categorySlug": "grassroots-journeys",
    "author": "Diego Martins",
    "publishedAt": "2026-09-27T10:06:05.633Z",
    "imageUrl": "https://images.unsplash.com/photo-1461896836934-ffe607ba6851?w=800&q=80",
    "readCount": 21519,
    "featured": false,
    "isVideo": true
  },
  {
    "id": "art-9",
    "slug": "por-que-grassroots-journeys-domina-a-conversa-e-o-que-vem-a-seguir-2l0",
    "title": "Por que grassroots journeys domina a conversa — e o que vem a seguir",
    "excerpt": "O que já está confirmado, o que ainda é especulação e o que acompanhar nas próximas horas.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Chute do Interior</strong> na seção <em>grassroots journeys</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "grassroots journeys",
    "categorySlug": "grassroots-journeys",
    "author": "Elena Prado",
    "publishedAt": "2026-09-27T03:06:05.633Z",
    "imageUrl": "https://images.unsplash.com/photo-1486286701208-1d58e9338013?w=800&q=80",
    "readCount": 22516,
    "featured": false,
    "isVideo": false
  }
];

export const alerts: AlertItem[] = [
  {
    "id": "alert-1",
    "level": "Urgente",
    "title": "Atualização crítica em Série C clubs — acompanhe minuto a minuto",
    "href": "/artigo/ultima-hora-em-serie-c-clubs-decisoes-que-mexem-com-a-rodada-2ks",
    "publishedAt": "2026-09-26T11:06:05.633Z"
  },
  {
    "id": "alert-2",
    "level": "Importante",
    "title": "Chute do Interior: comunicado oficial sobre cobertura em tempo real",
    "href": "/alertas",
    "publishedAt": "2026-09-29T04:06:05.634Z"
  },
  {
    "id": "alert-3",
    "level": "Aviso",
    "title": "Manutenção programada da área de alertas (demo)",
    "publishedAt": "2026-09-28T21:06:05.634Z"
  },
  {
    "id": "alert-4",
    "level": "Urgente",
    "title": "Desenvolvimento em regional stories com impacto nacional",
    "href": "/artigo/serie-c-clubs-em-foco-tres-leituras-que-importam-hoje-2kt",
    "publishedAt": "2026-09-28T14:06:05.634Z"
  },
  {
    "id": "alert-5",
    "level": "Importante",
    "title": "Fontes oficiais confirmam novo capítulo da história em acompanhamento",
    "publishedAt": "2026-09-28T07:06:05.634Z"
  },
  {
    "id": "alert-6",
    "level": "Aviso",
    "title": "Lembrete editorial: confira a política de atualização ao vivo",
    "href": "/sobre",
    "publishedAt": "2026-09-28T00:06:05.634Z"
  }
];

export const liveStories: LiveStory[] = [
  {
    "id": "live-1",
    "slug": "demo-nacional",
    "title": "AO VIVO — Cobertura nacional de Chute do Interior",
    "summary": "Linha do tempo demonstrativa com fontes rotuladas e âncoras estáveis.",
    "updatedAt": "2026-09-26T11:06:05.634Z",
    "updates": [
      {
        "id": "upd-1",
        "at": "2026-09-26T11:06:05.634Z",
        "source": "Redação",
        "text": "Início da cobertura ao vivo. Equipe monitora fontes oficiais e correspondentes."
      },
      {
        "id": "upd-2",
        "at": "2026-09-29T04:06:05.634Z",
        "source": "Agência",
        "text": "Primeira confirmação independente chega à mesa. Texto em verificação cruzada."
      },
      {
        "id": "upd-3",
        "at": "2026-09-28T21:06:05.634Z",
        "source": "Correspondente",
        "text": "Cena local descrita com cautela — sem especulação além do observado."
      },
      {
        "id": "upd-4",
        "at": "2026-09-28T14:06:05.634Z",
        "source": "Redação",
        "text": "Linha do tempo reorganizada. Âncoras de atualização permanecem estáveis."
      },
      {
        "id": "upd-5",
        "at": "2026-09-28T07:06:05.634Z",
        "source": "Especialista",
        "text": "Contexto rápido para leitores que acabaram de entrar na cobertura."
      },
      {
        "id": "upd-6",
        "at": "2026-09-28T00:06:05.634Z",
        "source": "Redação",
        "text": "Última atualização desta demonstração. Em produção, o CMS alimenta este feed."
      }
    ]
  },
  {
    "id": "live-2",
    "slug": "demo-regional",
    "title": "AO VIVO — Frente regional (br-bahia)",
    "summary": "Segundo demo de live-blog para validar rotas e UI.",
    "updatedAt": "2026-09-28T21:06:05.634Z",
    "updates": [
      {
        "id": "upd-r1",
        "at": "2026-09-28T21:06:05.634Z",
        "source": "Redação regional",
        "text": "Abertura do blog regional com foco em impacto local."
      },
      {
        "id": "upd-r2",
        "at": "2026-09-28T14:06:05.634Z",
        "source": "Prefeitura / órgão local (demo)",
        "text": "Nota oficial demonstrativa — rotular fonte é obrigatório neste layout."
      }
    ]
  }
];
